### ISSUE TITLE
graphql support

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/neo4j-decorator#11]
There is some effort going on to support GraphQL on Neo4j, cf.:

- https://github.com/neo4j-graphql/neo4j-graphql

What do you think? @alex-kuck @marcoh00 ?

**Comment by mkoertgen** [comment]
Check

- [graphql/express-graphql](https://github.com/graphql/express-graphql)

**Comment by PaulHindenberg** [comment]
Also check this graphQL middleware for Express, Koa and more

- [Apollo Server](https://github.com/apollographql/apollo-server)

**Comment by mkoertgen** [comment]
Added graphql plugin to the neo4j-container as an example, so playing around with graphql is easy now.

**Comment by mkoertgen** [comment]
Added graphql-plugin to the accompanying neo4j-container as an example

**Comment by alex-kuck** [comment]
Does not make sense to add the generic complexity of graphql to the decorations.
