### ISSUE TITLE
Docker Labels

### ISSUE THREAD

**Issue by alex-kuck** [awesome-inc/neo4j-decorator#18]
We should add labels to the Dockerfile.

**Comment by mkoertgen** [comment]
Added labels the same way as in https://github.com/awesome-inc/elastic_provisioner using official label schema and injecting `BUILD_DATE` via `hooks/build`.

Also changed base image to `9.11.1-alpine` reducing image size from 300MB to around 30MB.

Finally, fixed a minor bug on putting config/docs not using the request body.

**Comment by mkoertgen** [comment]
Cleaned up tags. Version 0.5.0 now looks good to me.
