### ISSUE TITLE
Add Drop-In capability for config and templates

### ISSUE THREAD

**Issue by alex-kuck** [awesome-inc/neo4j-decorator#20]
It should be possible to separate `.yml` files by topics or features. That would enable us to dynamically add new templates or context menus for new features.

**Comment by mkoertgen** [comment]
**Proposal:** 
- Add all yml-files from e.g. `/etc/neo4j-decorator/conf.d/**/*.yml`. For recursive e.g. use [micromatch/glob-fs](https://github.com/micromatch/glob-fs).
- Then merge them together e.g. using [KyleAMathews/deepmerge](https://github.com/KyleAMathews/deepmerge)
