### ISSUE TITLE
Docker buil can't cache with early labels

### ISSUE THREAD

**Issue by SchreiberLex** [awesome-inc/neo4j-decorator#31]
Building the Dockerimage does not use the Docker build cache as the labels contain ever changing information.

Moving the labeling to the end of the Dockerfile allows the caching to work.

**Comment by mkoertgen** [comment]
@SchreiberLex Great. Would you mind submitting a PR?

**Comment by mkoertgen** [comment]
@SchreiberLex Great. Do you need the image to be tagged and deployed?

**Comment by SchreiberLex** [comment]
As these changes are only changing the way the image is build i don't see a need for a new tagged version
