### ISSUE TITLE
Support new transactional endpoint and/or row/graph format

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/neo4j-decorator#4]
By now the decorator matches only results of the [legacy cypher endpoint](https://neo4j.com/docs/rest-docs/current/#rest-api-cypher) which will disappear sooner or later.

The new [transactional endpoint](http://neo4j.com/docs/developer-manual/3.1/http-api/#http-api-transactional) should be supported as well.

Maybe the [graph result format](http://neo4j.com/docs/developer-manual/3.1/http-api/#rest-api-return-results-in-graph-format) could be interesting to support as well.

**Comment by alex-kuck** [comment]
An example request using the new transactional endpoint could look as follows:

- **POST** http://localhost:3000/api/ai/graph/transaction/commit
- **Accept** application/json; charset=UTF-8
- **Content-Type** application/json
- **Body**
```
{
  "statements" : [
    {
      "statement" : "MATCH (n)-[e]-(v) where id(n)=1234 collect(n) as Nodes, collect(e) as Edges",
      "resultDataContents" : ["row", "graph"]
    } 
  ]
}
```
**NOTE:** `collect()` is used in order to flatten the resulting graph within the response. Otherwise one graph element is returned per resulting row.

**Comment by mkoertgen** [comment]
@alex-kuck Great, would you mind adding a test for the graph result format? You could start by duplicating the interpolate test from here [test/test.js#L26](https://github.com/awesome-inc/neo4j-decorator/blob/master/test/test.js#L26).

**Comment by mkoertgen** [comment]
Great. Since we now support testing adding a CI step for running the tests should be added.

**Comment by mkoertgen** [comment]
Here is an example config-snippet for the transactional endpoint that works for the APOC beginners example [Calling Procedures within Cypher](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_calling_procedures_within_cypher):

    decorate_transactional:
      Person:
        properties:
          links:
            - title: "Google '{{doc.properties.name}}'"
              href: 'https://www.google.de/search?q={{doc.properties.name}}'

Here's the example request:

    POST http://localhost:3000/api/ai/graph/transaction/commit
    {
       "statements" : [
       {
          "statement" : "WITH 'https://raw.githubusercontent.com/neo4j-contrib/neo4j-apoc-procedures/master/src/test/resources/person.json' AS url\nCALL apoc.load.json(url) YIELD value as person\nMERGE (p:Person {name:person.name})\nON CREATE SET p.age = person.age, p.children = size(person.children)\nRETURN p",
            "resultDataContents" : ["row", "graph"]
          } 
        ]
      }
    }
